"""add organization signup verification

Revision ID: 98258e712cc2
Revises: 0b9868d4efe2
Create Date: 2026-09-13 13:12:13.292508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '98258e712cc2'
down_revision: Union[str, Sequence[str], None] = '0b9868d4efe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # create_type=False on company_type/industry: those Postgres enum types
    # already exist (created by 0b9868d4efe2 for organizations.company_type/
    # industry) and are being reused here, not created fresh - see the
    # add_column-vs-create_table note in that revision for why this needs to
    # be explicit rather than left to autogenerate's default.
    op.create_table('organization_signup_requests',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('company_type', postgresql.ENUM('service_based', 'product_based', 'hybrid', name='company_type', create_type=False), nullable=False),
    sa.Column('industry', postgresql.ENUM('it_software', 'finance_banking', 'healthcare', 'education', 'retail_ecommerce', 'manufacturing', 'real_estate', 'hospitality_travel', 'media_entertainment', 'telecommunications', 'logistics_transportation', 'construction', 'energy_utilities', 'agriculture', 'government_public_sector', 'non_profit', 'consulting', 'legal', 'other', name='industry', create_type=False), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_signup_requests_email'), 'organization_signup_requests', ['email'], unique=True)
    op.create_index(op.f('ix_organization_signup_requests_id'), 'organization_signup_requests', ['id'], unique=False)
    op.create_index(op.f('ix_organization_signup_requests_token_hash'), 'organization_signup_requests', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_signup_requests_token_hash'), table_name='organization_signup_requests')
    op.drop_index(op.f('ix_organization_signup_requests_id'), table_name='organization_signup_requests')
    op.drop_index(op.f('ix_organization_signup_requests_email'), table_name='organization_signup_requests')
    op.drop_table('organization_signup_requests')
    # ### end Alembic commands ###
